theme: jekyll-theme-minimal
title: Tạo sự kiện âm lịch
description: Tạo file ICS cho sự kiện âm lịch để import vào Google Calendar, Outlook, Apple Calendar
url: https://anhquande.github.io/tao-su-kien-am-lich
baseurl: /tao-su-kien-am-lich
